# new client

NEW_CLIENT = dict(
    title="Miss",
    name="Paulina60",
    middle_name="Weronika",
    last_name="Murzanska60",
    gender="Female",
    insurance_no="AA128845A",
    email="p.murzanska60@gmail.com",
    tel_no="+44 009 999 998",
    bank_account="43456714",
    sort_code="123456",
    postcode="HD9 9PH",
    street="8 Zoe Motorway",
    city="Port Alice",
    county="Port Julie",
    country="United Kingdom",
    date_of_birth='08/03/1987',
    is_uk_resident=True,
    tax_return_abroad=False,
)
NEW_CLIENT_2 = dict(
    title="Miss",
    name="Paulina61",
    middle_name="Weronika",
    last_name="Murzanska61",
    gender="Female",
    insurance_no="AA128845A",
    email="p.murzanska61@gmail.com",
    tel_no="+44 009 999 998",
    bank_account="43456714",
    sort_code="123456",
    postcode="HD9 9PH",
    street="8 Zoe Motorway",
    city="Port Alice",
    county="Port Julie",
    country="United Kingdom",
    date_of_birth='08/03/1987',
    is_uk_resident=True,
    tax_return_abroad=False,
)
