# new client

NEW_CLIENT = dict(
    title="Miss",
    name="Paulina75",
    middle_name="Weronika",
    last_name="Murzanska75",
    gender="Female",
    insurance_no="AA128845A",
    email="p.murzanska75@gmail.com",
    tel_no="+44 009 999 998",
    bank_account="43456714",
    sort_code="123456",
    postcode="HD9 9PH",
    street="8 Zoe Motorway",
    city="Port Alice",
    county="Port Julie",
    country="United Kingdom",
    date_of_birth='08/03/1987',
    is_uk_resident=True,
    tax_return_abroad=False,
)
NEW_CLIENT_2 = dict(
    title="Miss",
    name="Paulina76",
    middle_name="Weronika",
    last_name="Murzanska76",
    gender="Female",
    insurance_no="AA128845A",
    email="p.murzanska76@gmail.com",
    tel_no="+44 009 999 998",
    bank_account="43456714",
    sort_code="123456",
    postcode="HD9 9PH",
    street="8 Zoe Motorway",
    city="Port Alice",
    county="Port Julie",
    country="United Kingdom",
    date_of_birth='08/03/1987',
    is_uk_resident=True,
    tax_return_abroad=False,
)
NEW_CLIENT_3 = dict(
    title="Miss",
    name="Paulina77",
    middle_name="Weronika",
    last_name="Murzanska77",
    gender="Female",
    insurance_no="AA128845A",
    email="p.murzanska77@gmail.com",
    tel_no="+44 009 999 998",
    bank_account="43456714",
    sort_code="123456",
    postcode="HD9 9PH",
    street="8 Zoe Motorway",
    city="Port Alice",
    county="Port Julie",
    country="United Kingdom",
    date_of_birth='08/03/1987',
    is_uk_resident=True,
    tax_return_abroad=False,
)
NEW_CLIENT_INCORRECT_DATA = dict(
    title="Miss",
    name="Paulina62",
    middle_name="Weronika",
    last_name="Murzanska62",
    gender="Female",
    insurance_no="AA128845A",
    email="p.murzanska@gmail.com",
    tel_no="+44 009 999 998",
    bank_account="43456714",
    sort_code="123456",
    postcode="HD9 9PH",
    street="8 Zoe Motorway",
    city="Port Alice",
    county="Port Julie",
    country="United Kingdom",
    date_of_birth='08/03/1987',
    is_uk_resident=True,
    tax_return_abroad=False,
)

ADVISING_FORM_DATA = dict(
    investor_type="1",
    tax_wrapper="1",
    payment_method="Bank transfer",
    initial_investment="12000",
    service_duration="2 years",
    income_frequency="Monthly",
    adviser_charge="10"
)

ADVISING_FORM_INCORRECT_DATA = dict(
    investor_type="1",
    tax_wrapper="1",
    payment_method="Bank transfer",
    initial_investment="500",
    service_duration="2 years",
    income_frequency="Monthly",
    adviser_charge="10"
)